version: '3.9'

services:
  nginx_fs:
    image: jwilder/nginx-proxy
    container_name: nginx_fs
    ports:
      - '7001:80'
    volumes:
      - ./planterium_file_server/static/images:/usr/share/nginx/images

  postgres:
    image: postgres:15.1-alpine
    container_name: postgres15.1-alpine
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=pavelbeard
      - POSTGRES_PASSWORD="Rt3%YiOO"
    volumes:
      - ./planterium_db_api/postgres_data:/docker-entrypoint-initdb.d
#      - ./planterium_db_api/postgres_data:/var/lib/postgresql/data
    ports:
      - "8001:5432"